### ISSUE TITLE
Dockerのオートセットアップ(hira-chan用)

### ISSUE THREAD

**Issue by sho037** [oithxs/hira-chan#192]
## 欲しい機能

hira-chanにrenameした人、新規の人用にリポジトリネームがhira-chanでも動作するシェルスクリプト
(/bin/setup-docker.shのような)

## 目的

hira-chanにrenameしたため、/bin/setup-docker.shが動作しなくなってしまったため、hira-chanでも動作することが可能な
セットアップシェルスクリプトを制作

## タスク

- [ ] hira-chan用docker setup.shを制作

## その他

できればホームディレクトリ以外でも動作するようにしてほしい

**Comment by Nave-wata** [comment]
環境構築にVSCodeのdevcontainerを利用することとなりましたので，`bin/setup-docker.sh` などのシェルスクリプトは削除しました．しかし，以前よりも容易に環境構築が行える様になったと思われます．

一般ユーザによるファイル作成などが出来るフォルダであれば，ホームディレクトリ以外でも動作する様になっているはずです．
