### ISSUE TITLE
アクセスランキングにもURLを

### ISSUE THREAD

**Issue by sho037** [oithxs/hira-chan#215]
## 欲しい機能

* アクセスランキングからでも各スレッドにアクセスできるように

## 目的

* アクセスランキングで気になったスレッドにアクセスをできるようにするため

## その他

* できればリンクの範囲を広げてクリックしやすくしておいてほしい

**Comment by Nave-wata** [comment]
フロントエンドを一新するため，新しいバージョンに切り変えました
ですので，コチラのプルリクエストはクローズさせていただきます．
